project:
  type: website

website:
  title: "Jordan Lewis-Morden"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: research.qmd
        text: Research & Policy
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false